# Generated by Django 4.0.6 on 2022-08-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('edad', models.IntegerField(null=True, verbose_name='Edad')),
                ('recorrido', models.TextField(null=True, verbose_name='Historia')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('portada', models.ImageField(null=True, upload_to='images/', verbose_name='Portada')),
                ('sinopsis', models.TextField(null=True, verbose_name='Sinopsis')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('usuario', models.CharField(max_length=25, verbose_name='UserName')),
                ('email', models.EmailField(max_length=50, verbose_name='correo')),
                ('password', models.CharField(max_length=50, verbose_name='contraseña')),
            ],
        ),
    ]
