# Generated by Django 4.0.6 on 2022-08-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesInventary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='portada',
            field=models.ImageField(null=True, upload_to='static/images/', verbose_name='Portada'),
        ),
    ]
