# Generated by Django 4.0.6 on 2022-08-05 03:53

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesInventary', '0004_alter_movie_managers_alter_usuario_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='movie',
            managers=[
                ('operacionesmanager', django.db.models.manager.Manager()),
            ],
        ),
    ]
