# Generated by Django 4.0.6 on 2022-08-06 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesInventary', '0007_alter_artista_managers_alter_movie_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
