# Generated by Django 4.0.6 on 2022-08-09 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesInventary', '0010_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
