# Generated by Django 4.0.6 on 2022-08-09 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesInventary', '0011_delete_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
