# Generated by Django 4.0.6 on 2022-08-10 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesInventary', '0013_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
